### ISSUE TITLE
Скрывать уведомления через 5 секунд

### ISSUE THREAD

**Issue by chekalskiy** [tjournal/chat#45]

**Comment by Kern0** [comment]
Уведомления браузерные? Я не уверен, что это возможно. Я не могу управлять их отображением вроде.

**Comment by strikeentco** [comment]
@Kern0 [Check it out] (https://developer.mozilla.org/en-US/docs/Web/API/Notification/close)

**Comment by Kern0** [comment]
Этого там не было :] Скоро будет
